version: '3.8'

services:
  core:
    build:
      context: .
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - NATS_HOST=nats
    ports:
      - ${PORT}:${PORT}

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    command: -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg:/var/lib/postgresql/data


volumes:
  pg:
    driver: local
